// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz60YcMXwUSWv8WnmLARcghROTSEwYJZ8',
    appId: '1:18163678586:web:067faf8b68cdd63bdaeac3',
    messagingSenderId: '18163678586',
    projectId: 'pooja-b46ef',
    authDomain: 'pooja-b46ef.firebaseapp.com',
    storageBucket: 'pooja-b46ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yfbcHZjyqYrd26SQTPK18PXh5QAycK8',
    appId: '1:18163678586:android:ca9c38edaa9b76b1daeac3',
    messagingSenderId: '18163678586',
    projectId: 'pooja-b46ef',
    storageBucket: 'pooja-b46ef.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXSsjFBUZF1sEKb2ObZPBIrZW-tf-5wws',
    appId: '1:18163678586:ios:dc3f805545311e8fdaeac3',
    messagingSenderId: '18163678586',
    projectId: 'pooja-b46ef',
    storageBucket: 'pooja-b46ef.firebasestorage.app',
    iosClientId: '18163678586-auug0ilebto10podh266lc93oe0t9m3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.poojaPundit',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXSsjFBUZF1sEKb2ObZPBIrZW-tf-5wws',
    appId: '1:18163678586:ios:dc3f805545311e8fdaeac3',
    messagingSenderId: '18163678586',
    projectId: 'pooja-b46ef',
    storageBucket: 'pooja-b46ef.firebasestorage.app',
    iosClientId: '18163678586-auug0ilebto10podh266lc93oe0t9m3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.poojaPundit',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz60YcMXwUSWv8WnmLARcghROTSEwYJZ8',
    appId: '1:18163678586:web:067faf8b68cdd63bdaeac3',
    messagingSenderId: '18163678586',
    projectId: 'pooja-b46ef',
    authDomain: 'pooja-b46ef.firebaseapp.com',
    storageBucket: 'pooja-b46ef.firebasestorage.app',
  );
}
